using System.Text.RegularExpressions;

namespace morse_auth
{
    /// <summary>
    /// Parameters for JWTs
    /// </summary>
    public static class TokenParams
    {
        public const string Issuer = "morse-security";
        public const string Audience = "morse-apps";

        /*
         * These keys were generated by
         * https://cryptotools.net/rsagen
         */
        private const string _privateKeyRaw = "-----BEGIN RSA PRIVATE KEY-----\r\nMIIEpAIBAAKCAQEAsunnY2cc15y1bTm87er8P3td+OOmIL2lGyCycLG3i2e8pvBz\r\n89Fh3Iln8jF4VWRdOgCZifYu+GxbND9x8N1BZK+H74WReMcRohoEMYIrnu/kf2Kx\r\nCZCd1Mtr0RmMxn35YONr33VDL8gyZI+LY/Qg0m+bQ3BXjyS15iNpmO1QaCRlpvg8\r\nV6fG0aZafk8t6Pdk+kZlEbqeLuYyigf5UEx2R5qfs5ahFC6Nje4iRkpe/3jmuDKX\r\naYv0ux0rNT92yC9vdkQTs4AUC5OiRNDuE+djoba9H5wNkyuoZAQqPp8K1IQFXTxA\r\nCr0mZw14ZZDw6xkK2wmG7+JbdMbp252covb9iwIDAQABAoIBAQCH+3WtvIpUajwO\r\nt2qcXhS43zguWkBC9EEQHErjkn+Rihf9vhYzQ3og16LUlrsCFBUzZ49LJ3zNvfWY\r\nAXzFeDUipLMp3pgRdyQ005dKVch3tZczJryuK2d6e94HgGbZ2pd3B4NOxN5666s5\r\neUyVfNCRgNg+ap1yI5HJSDMTU5Pggjv+niVNiJZ+bsvTqVedqXOm28TuMFWSZXof\r\noJzqB4H8WRQzlMO5vUka1t52hLOetOlykbb980DqSYAPs0qCVcoLAV4mlgZDx5Dx\r\n9eLqqNYIoNgiSxHZRnsCojYZgP0f+x9B0yg8WldcRQ6bfsCpVPR3MGR4advhaF5V\r\n+O8CXA3JAoGBANuGSIJDPTyAXryv1TVaGm7hsw7DWOWpfVcovU7Aa/lQtnpMJDnB\r\ntjhgGkh73YTOesYzd21b7JyNEBAikkH8JJ+YX4ZHfESQzJdpTkowq2l3Acz9E354\r\nMqvH5mLVxOhDzpBdk7SGRFd2ybKm40Re8AFSbZ3o//5sp2oGnFV7ONh/AoGBANCk\r\nMYDBmElEha8X3dlgi9gYdydSXlm9v2w7+HK0E61ABQ+yZ9XabFqAuLPmn9hRiwdd\r\nGFLjPyFDKByVOfv+LQH+HrmMnlaggcT9SEhaBJtKZang0ybkNIaKiyHEblumJ4Uu\r\n2LIrIVopl8g6v1pTlmPOkqFVN7pPmyZvYwj7ajT1AoGAN6reukGoxq3a2EhSbbwS\r\nlemgCW9aHKsVQMPw9YZwGwHvtCWYzhikR7l/EMBwVRwzIA2vDElSQAS5fQ33Pspc\r\n0yfFmXyJM63wY7jthHzBCvaFu2C1z81VNCB1+LwyuZ9wQ0WnjhC6Rd+2mBof6ZeV\r\njxBDAdczC2asMYPJoxejO6sCgYB4Mt/CCcYuD6fko59PqGtoZ0/d+3oXwVUSicos\r\nasobOZKw5FslvNxHl3jRS8Ay42dxKpTky76G7yWgsefh4SEU0M3qn7Rou7eHQVPv\r\nOs0EmevP3pJHCZmpGQ/muD/L1QFXnRGCM47XXrbux8mNxDIT9eJLx8h/MXV0wx8P\r\nAajCMQKBgQCJt+JsupEwf3CREe+aFMQHGVp0UzVcKWqWJI8sjPBQmmcc9U4VFKhi\r\nMr+jfLU88px9TAU7eBjUMBtOomlj2eCECndA1FJ8+JPtee1xGYDpAYc28JPyc61d\r\nQPTKSDOQakoSF463VRPjfEFtDeQUtPK/62ambTWC9DtZyBKmNFE52g==\r\n-----END RSA PRIVATE KEY-----";
        private const string _publicKeyRaw = "-----BEGIN PUBLIC KEY-----\r\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsunnY2cc15y1bTm87er8\r\nP3td+OOmIL2lGyCycLG3i2e8pvBz89Fh3Iln8jF4VWRdOgCZifYu+GxbND9x8N1B\r\nZK+H74WReMcRohoEMYIrnu/kf2KxCZCd1Mtr0RmMxn35YONr33VDL8gyZI+LY/Qg\r\n0m+bQ3BXjyS15iNpmO1QaCRlpvg8V6fG0aZafk8t6Pdk+kZlEbqeLuYyigf5UEx2\r\nR5qfs5ahFC6Nje4iRkpe/3jmuDKXaYv0ux0rNT92yC9vdkQTs4AUC5OiRNDuE+dj\r\noba9H5wNkyuoZAQqPp8K1IQFXTxACr0mZw14ZZDw6xkK2wmG7+JbdMbp252covb9\r\niwIDAQAB\r\n-----END PUBLIC KEY-----";
        public static string PrivateKey { get; } = Regex.Unescape(_privateKeyRaw).Trim();
        public static string PublicKey { get; } = Regex.Unescape(_publicKeyRaw).Trim();
    }
}
